src/student_info_site/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from accounts.api.urls import router as account_router
from subjects.api.urls import router as subject_router
from comments.api.urls import router as comment_router
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home_page, name='home'),
    url(r'^404', views.error_404, name='error_404'),
    url(r'^403', views.error_403, name='error_403'),
    url(r'^400', views.error_400, name='error_400'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^forum/', include('subforums.urls', namespace='forum')),
    url(r'^threads/', include('threads.urls', namespace='threads')),
    url(r'^search/', views.search, name='search'),
    url(r'^api/subforum/', include(
        'subforums.api.urls', namespace='subforum-api')),
    url(r'^api/thread/', include('threads.api.urls', namespace='thread-apis')),
    url(r'^api/account/',
        include(account_router.urls, namespace='account-api')),
    url(r'^api/accounts/',
        include('accounts.api.urls', namespace='accounts-api')),
    url(r'^student/', include('subjects.urls', namespace='student')),
    url(r'^student_admin/',
        include('admin_student.urls', namespace='student_admin')),
    url(r'^api/subject-mark/',
        include(subject_router.urls, namespace='subject-api')),
    url(r'^api/comment/',
        include(comment_router.urls, namespace='comment-api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/threads/api/urls.py
from django.conf.urls import url
from .views import (
    ThreadSearchView,
    UserThreadAPIView,
    PostLikeToggleApi,
    CheckLikeApi,
    DeleteThreadApi,
    PublishThreadApi
)

app_name = 'threads'

urlpatterns = [
    url(r'^search$', ThreadSearchView.as_view(), name='search'),
    url(r'^user$', UserThreadAPIView.as_view(), name='user_thread'),
    url(r'^(?P<pk>\d+)/like/$', PostLikeToggleApi.as_view(),
        name='like-toggle'),
    url(r'^(?P<pk>\d+)/check-like/$', CheckLikeApi.as_view(),
        name='check-like'),
    url(r'^(?P<pk>\d+)/delete/$', DeleteThreadApi.as_view(), name='delete'),
    url(r'^(?P<pk>\d+)/publish/$', PublishThreadApi.as_view(), name='publish'),
]

src/threads/urls.py
from django.conf.urls import url, include
from .views import (
    post_thread,
    thread_detail_view,
    ThreadUpdateView,
    pin_thread,
    UserThreadDraftList,
)

app_name = 'threads'

urlpatterns = [
    url(r'^show/(?P<pk>\d+)/$', thread_detail_view, name='detail'),
    url(r'^(?P<pk>\d+)/edit/$', ThreadUpdateView.as_view(), name='edit'),
    url(r'^(?P<thread_id>\d+)/pin/$', pin_thread, name='pin'),
    url(r'^draft/$', UserThreadDraftList.as_view(), name='draft'),
    url(r'^create/$', post_thread, name='create'),
    url(r'^comments/', include('comments.urls', namespace='comments')),
]

src/threads/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.utils.text import slugify
from subforums.models import Subforum
from accounts.models import StudentProfile


class Thread(models.Model):
    subforum = models.ForeignKey(Subforum, related_name='threads')
    title = models.CharField(max_length=350)
    content = models.TextField()
    content_html = models.TextField(editable=False, default='', blank=True)
    author = models.ForeignKey(StudentProfile, related_name='threads')
    likes = models.ManyToManyField(StudentProfile, related_name='thread_likes',
                                   blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    published_date = models.DateTimeField(blank=True, null=True)
    is_pinned = models.BooleanField(default=False)
    view_count = models.IntegerField(default=0)

    class Meta:
        db_table = 'Threads'

    def increase_view(self):
        self.view_count += 1
        self.save()

    def summarize_content(self):
        if len(self.content) > 30:
            return '{}....'.format(self.content[:30])
        return self.content

    def get_detail_link(self):
        return reverse('threads:detail', kwargs={'pk': self.pk})

    def get_image_file_name(self, filename):
        slug = slugify(self.title)
        return 'thread_images/{}-{}'.format(slug, filename)

    def get_publish_url(self):
        return reverse('thread-apis:publish', kwargs={'pk': self.pk})

    def get_like_url(self):
        return reverse('thread-apis:like-toggle', kwargs={'pk': self.pk})

    def get_delete_api_url(self):
        return reverse('thread-apis:delete', kwargs={'pk': self.pk})

    def get_check_like_url(self):
        return reverse('thread-apis:check-like', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


class ThreadImages(models.Model):
    thread = models.ForeignKey(Thread, related_name='images')
    image = models.ImageField(upload_to='thread_images/', )

    def delete(self, using=None, keep_parents=False):
        self.image.delete()
        super().delete(using=using, keep_parents=keep_parents)

    def __str__(self):
        return self.image.name

src/threads/forms.py
from django import forms
import bleach
from django.conf import settings
from .models import Thread, ThreadImages


class ThreadForm(forms.ModelForm):
    class Meta:
        model = Thread
        fields = ('title', 'subforum', 'content',)
        widgets = {
            'content': forms.Textarea(attrs={
                'style': '',
                'class': 'editable medium-editor-textarea'}),
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'subforum': forms.Select(attrs={'class': 'form-control'}),
        }

    def clean_content(self):
        content = self.cleaned_data.get('content', '')
        cleaned_content = bleach.clean(text=content,
                                       tags=settings.BLEACH_VALID_TAGS,
                                       attributes=settings.BLEACH_VALID_ATTRS,
                                       styles=settings.BLEACH_VALID_STYLES,
                                       protocols=settings.BLEACH_VALID_PROTOCOLS)
        return cleaned_content

    def clean_title(self):
        title = self.cleaned_data.get('title', '')
        cleaned_title = bleach.clean(text=title,
                                     tags=settings.BLEACH_VALID_TAGS,
                                     attributes=settings.BLEACH_VALID_ATTRS,
                                     styles=settings.BLEACH_VALID_STYLES,
                                     protocols=settings.BLEACH_VALID_PROTOCOLS)
        return cleaned_title


class ImageForm(forms.ModelForm):
    image = forms.ImageField(label='image')

    class Meta:
        model = ThreadImages
        fields = ('image',)

src/threads/api/views.py
from enum import Enum

from django.db.models import Q
from django.db.models.aggregates import Count
from django.shortcuts import get_object_or_404
from django.urls.base import reverse
from django.utils import timezone
from django.utils.text import slugify
from rest_framework import authentication, permissions
from rest_framework import generics
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView

from threads.api import permissions as thread_permissions
from threads.models import Thread
from .pagination import StandardResultsPagination, UserThreadCommentPagination
from .serializers import ThreadModelSerializer

SUBFORUM_ALL_SELECT = 'All'


class SearchFilter(Enum):
    none_selected = 'None'
    top_comment = 'Most commented'
    view_increase = 'Total views ascending'
    view_decrease = 'Total views descending'
    like_increase = 'Total likes ascending'
    like_decrease = 'Total likes descending'


class ThreadSearchView(generics.ListAPIView):
    serializer_class = ThreadModelSerializer
    pagination_class = StandardResultsPagination

    def get_queryset(self):
        query = self.request.GET.get('query', '')
        subforum_key = self.request.GET.get('subforum', SUBFORUM_ALL_SELECT)
        filter_key = self.request.GET.get('filter',
                                          SearchFilter.none_selected.value)
        queryset = Thread.objects.filter(
            Q(content__icontains=query) |
            Q(title__icontains=query)
        ).order_by('-created_date')
        if subforum_key != SUBFORUM_ALL_SELECT:
            subforum_key = slugify(subforum_key)
            queryset = queryset.filter(subforum__slug__iexact=subforum_key)
        if filter_key == SearchFilter.top_comment.value:
            queryset = queryset.annotate(
                total_comment=Count('comments')
            ).order_by('-total_comment')
        if filter_key == SearchFilter.view_decrease.value:
            queryset = queryset.order_by('-view_count')
        if filter_key == SearchFilter.view_increase.value:
            queryset = queryset.order_by('view_count')
        if filter_key == SearchFilter.like_decrease.value:
            queryset = queryset.annotate(total_like=Count('likes')).order_by(
                '-total_like')
        if filter_key == SearchFilter.like_increase.value:
            queryset = queryset.annotate(total_like=Count('likes')).order_by(
                'total_like')
        return queryset


class UserThreadAPIView(generics.ListAPIView):
    serializer_class = ThreadModelSerializer
    pagination_class = UserThreadCommentPagination

    def get_queryset(self):
        student_id = self.request.GET.get('student_id', '')
        queryset = Thread.objects.filter(published_date__isnull=False,
                                         author__student_id=student_id)
        return queryset


class PostLikeToggleApi(APIView):
    authentication_classes = (authentication.SessionAuthentication,)
    permission_classes = (permissions.IsAuthenticated,)

    def put(self, request, pk=None):
        thread = get_object_or_404(Thread, pk=pk)
        user = self.request.user
        updated = False
        liked = False
        has_liked = thread.likes.filter(
            student_id=request.user.student_id).exists()
        if has_liked:
            liked = False
            thread.likes.remove(user)
        else:
            liked = True
            thread.likes.add(user)
        updated = True
        like_count = thread.likes.count()
        data = {
            'updated': updated,
            'liked': liked,
            'like_count': like_count,
        }
        return Response(data, status=status.HTTP_200_OK)


class CheckLikeApi(APIView):
    authentication_classes = (authentication.SessionAuthentication,)

    def get(self, request, pk, format=None):
        thread = get_object_or_404(Thread, pk=pk)
        if request.user.is_authenticated:
            has_liked = thread.likes.filter(
                student_id=request.user.student_id).exists()
        else:
            has_liked = False
        like_count = thread.likes.count()

        data = {
            'is_liked': has_liked,
            'like_count': like_count,
        }

        return Response(data, status=status.HTTP_200_OK)


class DeleteThreadApi(APIView):
    authentication_classes = (authentication.SessionAuthentication,)
    permission_classes = (
        permissions.IsAuthenticated,
        thread_permissions.DeleteOwnThreadComment
    )

    def delete(self, request, pk):
        thread = get_object_or_404(Thread, pk=pk)
        subforum_slug = thread.subforum.slug
        redirect_link = reverse('forum:detail', kwargs={'slug': subforum_slug})
        thread.delete()
        data = {
            'success': True,
            'redirect_link': redirect_link,
        }
        return Response(data, status=status.HTTP_200_OK)


class PublishThreadApi(APIView):
    authentication_classes = (authentication.SessionAuthentication,)
    permission_classes = (permissions.IsAuthenticated, permissions.IsAdminUser)

    def put(self, request, pk):
        thread = get_object_or_404(Thread, pk=pk)
        thread.published_date = timezone.now()
        thread.save()
        data = {
            'success': True,
        }
        return Response(data, status=status.HTTP_200_OK)

src/threads/views.py
from braces.views._access import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.urlresolvers import reverse
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView
from django.utils import timezone
from . import forms
from . import mixins
from .models import Thread, ThreadImages

THREADS_PER_PAGE = 7


class ThreadUpdateView(LoginRequiredMixin, mixins.UserOwnerMixin, UpdateView):
    model = Thread
    template_name = 'threads/thread-edit.html'
    context_object_name = 'thread'
    form_class = forms.ThreadForm
    login_url = 'accounts/login-site'

    def form_valid(self, form):
        if 'new-images' in self.request.FILES:
            images = self.request.FILES.getlist('new-images')
            threads = [ThreadImages(thread=self.object, image=image) for image
                       in images]
            ThreadImages.objects.bulk_create(threads)
        images_to_delete = self.request.POST.getlist('image-to-delete')
        ThreadImages.objects.filter(pk__in=images_to_delete).delete()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('threads:detail', kwargs={'pk': self.object.pk})


@login_required(login_url='/accounts/login-site/')
def pin_thread(request, thread_id):
    try:
        thread = Thread.objects.get(pk=thread_id)
    except:
        return render(request, 'error_404.html')
    thread.is_pinned = False if thread.is_pinned else True
    thread.save()
    return HttpResponseRedirect(
        reverse('threads:detail', kwargs={'pk': thread_id}))


def thread_detail_view(request, pk):
    try:
        thread = Thread.objects.get(pk=pk)
    except:
        return render(request, 'error_404.html')
    if not thread.published_date:
        if not request.user.is_superuser and not request.user == thread.author:
            return render(request, 'error_403.html')
    thread.increase_view()
    comment_list = thread.comments.all()
    page = request.GET.get('page', 1)
    paginator = Paginator(comment_list, 7)
    try:
        comments = paginator.page(page)
    except PageNotAnInteger:
        comments = paginator.page(1)
    except EmptyPage:
        comments = paginator.num_pages(paginator.num_pages)
    context_dict = {
        'thread': thread,
        'comment_list': comments,
    }
    return render(request, 'threads/thread-detail.html', context_dict)


class ThreadCreateView(LoginRequiredMixin, CreateView):
    login_url = '/accounts/login-site/'
    redirect_field_name = 'next'
    form_class = forms.ThreadForm
    model = Thread
    template_name = 'threads/thread-create.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('threads:detail', kwargs={'pk': self.object.pk})


class UserThreadDraftList(LoginRequiredMixin, ListView):
    model = Thread
    login_url = '/accounts/login-site'
    template_name = 'threads/draft_list.html'
    context_object_name = 'thread_list'

    def get_queryset(self):
        draft_list = Thread.objects.filter(published_date__isnull=True,
                                           author=self.request.user
                                           ).order_by('-created_date')
        page = self.request.GET.get('page', 1)
        paginator = Paginator(draft_list, THREADS_PER_PAGE)
        try:
            threads = paginator.page(page)
        except PageNotAnInteger:
            threads = paginator.page(1)
        except EmptyPage:
            threads = paginator.num_pages(paginator.num_pages)
        return threads


@login_required(login_url='/accounts/login-site/')
def post_thread(request):
    thread_form = forms.ThreadForm()
    if request.method == 'POST':
        thread_form = forms.ThreadForm(request.POST)
        if thread_form.is_valid():
            thread = thread_form.save(commit=False)
            thread.author = request.user
            if request.user.is_superuser:
                thread.published_date = timezone.now()
            thread_form.save()

            if 'images' in request.FILES:
                images = request.FILES.getlist('images')
                threads = [ThreadImages(thread=thread, image=image) for image
                           in images]
                ThreadImages.objects.bulk_create(threads)
            if request.user.is_superuser:
                return HttpResponseRedirect(reverse('threads:detail',
                                                    kwargs={'pk': thread.pk}))
            return HttpResponseRedirect(reverse('threads:draft'))
    return render(request, 'threads/thread-create.html',
                  {'thread_form': thread_form, })

src/threads/templates/threads/draft_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    {{ subforum.title }}
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/subforum-detail.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="page-header">
            <div class="row">
                <div class="col-md-6">
                    <strong
                        style="font-size: 1.5em">Your draft list
                    </strong>
                </div>

            </div>
        </div>
        <a id="thread_counter" data-href="{{ thread_list | length }}"></a>
        {% for thread in thread_list %}
            <div class="row">
                {% include 'subforums/thread-item.html' with thread=thread %}
            </div>
        {% empty %}
            <h4>There are no thread</h4>
        {% endfor %}
        <div class="row pull-right" style="margin-right: 24px;">
            {% if thread_list.has_other_pages %}
                <ul class="pagination">
                    {% if thread_list.has_previous %}
                        <li><a
                            href="?page={{ thread_list.previous_page_number }}">&laquo;</a>
                        </li>
                    {% else %}
                        <li class="disabled"><span>&laquo;</span></li>
                    {% endif %}
                    {% for i in thread_list.paginator.page_range %}
                        {% if thread_list.number == i %}
                            <li class="active"><span>{{ i }} <span
                                class="sr-only">(current)</span></span>
                            </li>
                        {% else %}
                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if thread_list.has_next %}
                        <li><a
                            href="?page={{ thread_list.next_page_number }}">&raquo;</a>
                        </li>
                    {% else %}
                        <li class="disabled"><span>&raquo;</span></li>
                    {% endif %}
                </ul>
            {% endif %}
        </div>
    </div>
    {% include 'delete-confirm-modal.html' %}
    {% include 'delete-confirm-modal.html' %}
{% endblock %}

{% block script %}
    <script src="{% static 'js/publish.js' %}"></script>
{% endblock %}

src/threads/templates/threads/thread-create.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block title %}
    Create new Thread
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/thread.css' %}">
    <link rel="stylesheet" href="{% static 'css/thread_create.css' %}">
{% endblock %}

{% block content %}
    <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-info">
            <div class="panel-heading">
                Create a new thread
            </div>
            <div class="panel-body">
                <form method="post" class="form-group"
                      enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ thread_form.as_p }}
                    <input type="file" multiple name="images" accept="image/*"
                           class="text-info">
                    <button type="submit"
                            class="btn btn-info btn-upload col-md-2 col-md-offset-5">
                        Create
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script>
        let editor = new MediumEditor('.editable');
    </script>
{% endblock %}

src/threads/templates/threads/thread-detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    {{ thread.title }}
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/thread.css' %}">
    <link rel="stylesheet" href="{% static 'css/thread_images.css' %}">
    <link rel="stylesheet" href="{% static 'css/comment.css' %}">
{% endblock %}

{% block content %}
    {% include 'threads/thread_detail_header.html' with thread=thread %}

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2 class="page-header">Comments</h2>
                <section id="commentSection"
                         total-comment="{{ comment_list | length }}"
                         class="comment-list">
                    <!-- First Comment -->
                    {% for comment in comment_list %}
                        <article class="row comment">
                            <div class="col-md-2 col-sm-2 hidden-xs">
                                <figure class="thumbnail">
                                    <img
                                        class="img-responsive img-comment img-circle"
                                        src="{{ comment.author.profile_pic.url }}"/>
                                    <figcaption class="text-center"
                                                style="margin-top: 10px">
                                        <a href="{{ comment.author.get_activity_link }}">
                                            {{ comment.author }}
                                        </a>
                                    </figcaption>
                                </figure>
                            </div>
                            <div class="col-md-10 col-sm-10">
                                <div class="panel panel-default arrow left">
                                    <div class="panel-body">
                                        <header class="text-left">
                                            <time class="comment-date"
                                                  datetime="16-12-2014 01:05">
                                                {{ comment.created_date }}
                                            </time>
                                            <hr/>
                                        </header>
                                        <div class="comment-post">
                                            <div id="comment-{{ comment.pk }}">
                                                {{ comment.content|safe |linebreaksbr }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="comment-option">
                                        {% if user.is_superuser or comment.author == user %}
                                            <p class="text-right">
                                            <a
                                                class="btn btn-info btn-sm btn-comment"
                                                id="btnEditComment-{{ forloop.counter }}"
                                                href="{% url 'threads:comments:edit-comment' pk=comment.pk %}"
                                                comment-id="{{ comment.pk }}"
                                                csrf-token="{{ csrf_token }}">
                                                Edit
                                            </a>
                                            <a
                                                id="btnDeleteComment-{{ forloop.counter }}"
                                                comment-id="{{ comment.pk }}"
                                                csrf-token="{{ csrf_token }}"
                                                href="#"
                                                class="btn btn-danger btn-sm btn-comment">
                                                Delete
                                            </a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </article>
                        <hr/>
                    {% empty %}
                    {% endfor %}
                </section>
                <div class="row pull-right" style="margin-right: 24px;">
                    {% if comment_list.has_other_pages %}
                        <ul class="pagination">
                            {% if comment_list.has_previous %}
                                <li><a
                                    href="?page={{ comment_list.previous_page_number }}">&laquo;</a>
                                </li>
                            {% else %}
                                <li class="disabled"><span>&laquo;</span></li>
                            {% endif %}
                            {% for i in comment_list.paginator.page_range %}
                                {% if comment_list.number == i %}
                                    <li class="active"><span>{{ i }} <span
                                        class="sr-only">(current)</span></span>
                                    </li>
                                {% else %}
                                    <li><a href="?page={{ i }}">{{ i }}</a>
                                    </li>
                                {% endif %}
                            {% endfor %}
                            {% if comment_list.has_next %}
                                <li><a
                                    href="?page={{ comment_list.next_page_number }}">&raquo;</a>
                                </li>
                            {% else %}
                                <li class="disabled"><span>&raquo;</span></li>
                            {% endif %}
                        </ul>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% include 'reply-thread-modal.html' with thread=thread %}
    {% include 'delete-confirm-modal.html' %}
{% endblock %}

{% block script %}
    <script src="{% static 'js/thread_detail_delete.js' %}"></script>
    <script src="{% static 'js/thread_images.js' %}"></script>
    <script src="{% static 'js/thread_reply.js' %}"></script>
{% endblock %}

src/threads/templates/threads/thread_detail_header.html
<div class="container-fluid">
    <div class="well" style="margin: 20px">
        <div class="row">
            <div class="col-md-12">
                <div class="col-md-3 col-xs-12 thumb-contenido">
                    <img class="thumbnail center-block img-responsive"
                         src="{{ thread.author.profile_pic.url }}"
                         style="width: 200px;height: 200px"/>
                    <hr>
                    <div class="text-center">
                        <small>{{ thread.created_date }}</small>
                        <br>
                        <small><strong><a
                            href="{{ thread.author.get_activity_link }}">{{ thread.author }}</a>
                        </strong></small>
                    </div>
                </div>
                <div>
                    <div class="">
                        <h3 class="hidden-xs hidden-sm">{{ thread.title }}</h3>
                        <span class="glyphicon glyphicon-heart"></span>
                        <span
                            id="like-counter">{{ thread.likes.count }}</span>
                        <button
                            class="btn btn-info glyphicon glyphicon-thumbs-up"
                            csrf-token="{{ csrf_token }}"
                            id="like-btn"
                            thread-id="{{ thread.pk }}"
                            check-like-url="{{ thread.get_check_like_url }}"
                            like-url="{{ thread.get_like_url }}">
                            Like
                        </button>
                    </div>
                    <hr>
                    <p class="text-justify">{{ thread.content |safe|linebreaksbr }}</p>
                </div>
            </div>
        </div>
        {% if thread.images.all %}
            {% include 'threads/thread_images.html' with images=thread.images.all %}
        {% endif %}
        <div class="panel-footer">
            <div class="row">
                <div class="pull-right">
                    {% if user.is_superuser %}

                        <a href="{% url 'threads:pin' thread_id=thread.pk %}"
                           class="btn btn-info btn-option btn-sm">
                            {% if thread.is_pinned %}
                                Unpin
                            {% else %}
                                Pin
                            {% endif %}
                        </a>
                    {% endif %}
                    {% if user == thread.author or user.is_superuser %}
                        <a id="btnDeleteThread"
                           thread-id="{{ thread.pk }}"
                           csrf-token="{{ csrf_token }}"
                           class="btn btn-danger btn-option btn-sm">Delete</a>
                        <a href="{% url 'threads:edit' pk=thread.pk %}"
                           class="btn btn-warning btn-option btn-sm">Edit</a>
                    {% endif %}
                    <a id="btnQuickReply"
                       class="btn btn-primary btn-option btn-sm">Quick
                        Reply</a>
                    <a href="{% url 'threads:comments:post-comment' pk=thread.pk %}"
                       class="btn btn-primary btn-option btn-sm">Reply</a>
                </div>
            </div>
        </div>
    </div>
</div>