src/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from .views import (
    user_profile,
    user_profile_edit,
    update_profile,
    user_login,
    change_password,
    user_activity,
)
from .resetpass import ResetPasswordRequestView, PasswordResetConfirmView

app_name = 'accounts'

urlpatterns = [
    url(r'^login-site/', user_login, name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^password-change/$', change_password, name='password-change'),
    url(r'^(?P<student_id>\d+)/profile/$', user_profile, name='profile'),
    url(r'^(?P<student_id>\d+)/activity/$', user_activity, name='activity'),
    url(r'^(?P<student_id>\d+)/profile/edit/$', user_profile_edit,
        name='profile-edit'),
    url(r'^(?P<student_id>\d+)/profile/api/update-info/$', update_profile,
        name='profile-update'),
    url(r'^reset_password/$', ResetPasswordRequestView.as_view(),
        name='reset_password'),
    url(
        r'^reset_password_confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        PasswordResetConfirmView.as_view(), name='reset_password_confirm')
]

src/admin_student/urls.py
from django.conf.urls import url

from . import views

app_name = 'student_admin'

urlpatterns = [
    url(r'^subforum/(?P<slug>[-\w]+)/drafts/$', views.subforum_draft_list,
        name='drafts'),
    url(r'^index/$', views.UserListView.as_view(), name='user-list'),
    url(r'^subject/$', views.SubjectListView.as_view(), name='subject-list'),
    url(r'^user/(?P<student_id>\d+)/transcript/$',
        views.MarkListView.as_view(), name='transcript'),
]

src/student_info_site/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from accounts.api.urls import router as account_router
from subjects.api.urls import router as subject_router
from comments.api.urls import router as comment_router
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home_page, name='home'),
    url(r'^404', views.error_404, name='error_404'),
    url(r'^403', views.error_403, name='error_403'),
    url(r'^400', views.error_400, name='error_400'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^forum/', include('subforums.urls', namespace='forum')),
    url(r'^threads/', include('threads.urls', namespace='threads')),
    url(r'^search/', views.search, name='search'),
    url(r'^api/subforum/', include(
        'subforums.api.urls', namespace='subforum-api')),
    url(r'^api/thread/', include('threads.api.urls', namespace='thread-apis')),
    url(r'^api/account/',
        include(account_router.urls, namespace='account-api')),
    url(r'^api/accounts/',
        include('accounts.api.urls', namespace='accounts-api')),
    url(r'^student/', include('subjects.urls', namespace='student')),
    url(r'^student_admin/',
        include('admin_student.urls', namespace='student_admin')),
    url(r'^api/subject-mark/',
        include(subject_router.urls, namespace='subject-api')),
    url(r'^api/comment/',
        include(comment_router.urls, namespace='comment-api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/subforums/urls.py
from django.conf.urls import url
from .views import SubforumListView, subforum_detail

app_name = 'forum'

urlpatterns = [
    url(r'^$', SubforumListView.as_view(), name='list'),
    url(r'^(?P<slug>[-\w]+)/$', subforum_detail, name='detail'),
]

src/subjects/urls.py
from django.conf.urls import url
from .views import SubjectListView

app_name = 'student'

urlpatterns = [
    url(r'^transcript/$', SubjectListView.as_view(), name='transcript'),
]

src/threads/urls.py
from django.conf.urls import url, include
from .views import (
    post_thread,
    thread_detail_view,
    ThreadUpdateView,
    pin_thread,
    UserThreadDraftList,
)

app_name = 'threads'

urlpatterns = [
    url(r'^show/(?P<pk>\d+)/$', thread_detail_view, name='detail'),
    url(r'^(?P<pk>\d+)/edit/$', ThreadUpdateView.as_view(), name='edit'),
    url(r'^(?P<thread_id>\d+)/pin/$', pin_thread, name='pin'),
    url(r'^draft/$', UserThreadDraftList.as_view(), name='draft'),
    url(r'^create/$', post_thread, name='create'),
    url(r'^comments/', include('comments.urls', namespace='comments')),
]

src/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/master.css' %}">
        <link rel="stylesheet"
              href="{% static 'bootstrap/css/bootstrap.min.css' %}">
        <script src="{% static 'jquery/jquery3.2.1.min.js' %}"></script>
        <script src="{% static 'js/waiting_dialog.js' %}"></script>
        <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">
        <!-- Latest compiled and minified JavaScript -->
        <script
            src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js"></script>
        <link
            rel="stylesheet"
            href="//cdn.jsdelivr.net/medium-editor/latest/css/medium-editor.min.css"
            type="text/css"
            media="screen" charset="utf-8">
        <link rel="stylesheet"
              href="{% static 'bootstrap/font-awesome.min.css' %}">
        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
        {% block css %}{% endblock %}
    </head>
    <body>
        {% include 'navbar.html' with user=user %}
        <div class="container-fluid" style="margin-top: 70px">
            {% block content %}{% endblock %}
        </div>
        <footer style="margin-top: 50px">
            <div class="container">
                <div class="text-center">
                    Hanoi University of Science and Technology 2017
                </div>
            </div>
        </footer>
    </body>

    <script src="{% static 'js/like.js' %}"></script>
    <script
        src="//cdn.jsdelivr.net/medium-editor/latest/js/medium-editor.min.js">
    </script>
    {% block script %}{% endblock %}

</html>

src/templates/delete-confirm-modal.html
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        aria-label="Close"><span
                    aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="replyModalLabel">
                    Are you sure???
                </h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete (this)?</p>
                <div class="row">
                    <div class="col-12-xs text-center">
                        <button id="btnDelete"
                                class="btn btn-success btn-md">
                            Yes
                        </button>
                        <button id="btnCancelDelete"
                                data-dismiss="modal"
                                class="btn btn-danger btn-md">No
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/templates/error.html
{% extends 'base.html' %}

{% block title %}
    Oops!
{% endblock %}



{% block content %}
    <div class="container">
        <div class="jumbotron">
            <div class="text-center"><i
                class="glyphicon glyphicon-exclamation-sign"
                style="color:#d9534f;"></i></div>
            <h1 class="text-center">Permission Denied<p></p>
                <p>
                    <small class="text-center"> Oh noes everything broke
                    </small>
                </p>
            </h1>
            <p class="text-center">You don't have permission to access this
                page</p>
            <p class="text-center"><a class="btn btn-primary"
                                      href="{% url 'home' %}"><i
                class="glyphicon glyphicon-home"></i> Take Me Home</a></p>
        </div>
    </div>
{% endblock %}

src/templates/error_400.html
{% extends 'base.html' %}

{% block title %}
    Oops!
{% endblock %}



{% block content %}
    <div class="container">
        <div class="jumbotron">
            <div class="text-center"><i
                class="glyphicon glyphicon-exclamation-sign"
                style="color:#d9534f;"></i></div>
            <h1 class="text-center">400 Bad Request<p></p>
                <p>
                    <small class="text-center"> Oh noes everything broke
                    </small>
                </p>
            </h1>
            <p class="text-center">You don't have permission to access this
                page</p>
            <p class="text-center"><a class="btn btn-primary"
                                      href="{% url 'home' %}"><i
                class="glyphicon glyphicon-home"></i> Take Me Home</a></p>
        </div>
    </div>
{% endblock %}

src/templates/error_403.html
{% extends 'base.html' %}

{% block title %}
    Oops!
{% endblock %}



{% block content %}
    <div class="container">
        <div class="jumbotron">
            <div class="text-center"><i
                class="glyphicon glyphicon-exclamation-sign"
                style="color:#d9534f;"></i></div>
            <h1 class="text-center">403 Forbidden<p></p>
                <p>
                    <small class="text-center"> Oh noes everything broke
                    </small>
                </p>
            </h1>
            <p class="text-center">You don't have permission to access this
                page</p>
            <p class="text-center"><a class="btn btn-primary"
                                      href="{% url 'home' %}"><i
                class="glyphicon glyphicon-home"></i> Take Me Home</a></p>
        </div>
    </div>
{% endblock %}

src/templates/error_404.html
{% extends 'base.html' %}

{% block title %}
    Oops!
{% endblock %}

{% block content %}
    <div class="container">
        <div class="jumbotron">
            <div class="text-center"><i
                class="glyphicon glyphicon-exclamation-sign"
                style="color:#d9534f;"></i></div>
            <h1 class="text-center">404 Not Found~<p></p>
                <p>
                    <small class="text-center"> Oh noes everything broke
                    </small>
                </p>
            </h1>
            <p class="text-center">We couldn't find the page</p>
            <p class="text-center"><a class="btn btn-primary"
                                      href="{% url 'home' %}"><i
                class="glyphicon glyphicon-home"></i> Take Me Home</a></p>
        </div>
    </div>
{% endblock %}

src/templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    SIS
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <!-- left section -->
        <div class="col-md-8">
            <div class="page-header">
                <h1><strong>Welcome</strong></h1>
            </div>
            <h4 class="plain-text" style="margin-top:24px;">This
                forum is
                useful for the beginners to get information related to
                various topics. There is a centralized database in which
                all the information is managed. The administrator acts as
                the highest authority and has the rights to update the
                database. There are also connected user who acts as an
                intermediate user who can also answer the questions of the
                end-user if they know it. The intermediate user can also
                cache the information provided by the administrator to the
                end-user. This cached information is useful when the same
                question is repeated some another user , then the
                intermediate user can get the information from cache memory
                and reply to the end-user. This reduces the response time.
                Whenever a question is asked by the end-user to get
                information ,it is received by the administrator who
                fetches the information from the database and reply to the
                end-user. Whenever the new information is arrived it is
                updated by the end-user. The end-user is provided with the
                access rights which is managed by the administrator. The
                access to the database is provided to the end-user
                according to these rights only.
            </h4>
        </div>
        <!-- right section -->
        <div class="col-md-4">
            <!-- Featured panel -->
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h4>Featured Forums</h4>
                </div>
                <div class="panel-body">
                    <div class="single category">
                        <ul class="list-unstyled">
                            {% for subforum in subforum_list %}
                                <li>
                                    <a
                                        href="{{ subforum.get_detail_link }}"
                                        title="">{{ subforum.title }}
                                        <span class="pull-right">
                                                {{ subforum.published_thread_count }}
                                            </span>
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <!-- Newsletter panel -->
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h4>Newsletter</h4>
                </div>
                <div class="panel-body">
                    <p>Use your student account to log in</p>
                </div>
            </div>
        </div>            <!-- /right section -->
    </div>            <!-- /row -->
{% endblock %}

src/templates/navbar.html
<nav class="navbar navbar-inverse navbar-fixed-top " style="height: 60px">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand"
               href="{% url 'home' %}">
                <span class="glyphicon glyphicon-home"></span>
                Homepage
            </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse"
             style="background-color: #222;padding-top: 4px">
            <ul class="nav navbar-nav">
                <li>
                    <a class="navbar-link"
                       href="{% url 'forum:list' %}">
                        <span class="glyphicon glyphicon-comment"></span>
                        Forum
                    </a>
                </li>
                {% if user.is_authenticated %}
                    <li>
                        <a class="navbar-link"
                           href="{% url 'student:transcript' %}">
                            <span class="glyphicon glyphicon-book"></span>
                            Transcript
                        </a>
                    </li>
                {% endif %}
            </ul>
            <form id="searchBar" class="navbar-form navbar-left" method="get"
                  action="{% url 'search' %}">
                <div class="form-group form-group-sm">
                    <input id="inputSearch" name="query"
                           class="text-info search-query form-control"
                           type="text"
                           placeholder="Search"
                           value="{{ request.GET.search }}">
                    <button class="btn btn-info btn-sm" type="submit">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    {% if user.is_superuser %}
                        <li>
                            <a
                                href="{% url 'student_admin:user-list' %}">
                                Admin
                            </a>
                        </li>
                    {% endif %}
                    <li><a href="{% url 'threads:draft' %}">Drafts</a></li>
                    <li>
                        <a href="{% url 'accounts:profile' student_id=user.student_id %}">
                            <img
                                width="25px" height="25px"
                                class="img-responsive img-circle"
                                src="{{ user.profile_pic.url }}">
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:profile' student_id=user.student_id %}">
                            <span
                                style="background-image: url('{{ user.profile_pic.url }}');"></span>
                            {{ user.name }}</a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:logout' %}">
                            <span class="glyphicon glyphicon-log-out"></span>
                            Log out
                        </a>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'accounts:login' %}">
                            <span class="glyphicon glyphicon-log-in"></span>
                            Login
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
    </div><!-- /.container-fluid -->
</nav>

src/templates/reply-thread-modal.html
<!-- Modal -->
<div class="modal fade" id="replyModal" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <form method="post" class="form tweet-form"
              action="{% url 'threads:comments:post-comment' pk=thread.pk %}">
            {% csrf_token %}
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"
                            aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="replyModalLabel">
                        Reply to "{{ thread.title }}"
                    </h4>
                </div>
                <div class="modal-body">
                    <textarea id="tweetReplyArea" class="form-control"
                              name="content"></textarea>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default"
                            data-dismiss="modal">Close
                    </button>
                    <button type="submit" class="btn btn-primary">Reply
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

src/templates/search_bar.html
<div class="container">
    <div class="row">
        <div class="col-md-12">

        </div>
    </div>
</div>

src/templates/search_form.html
<form id="searchBar" class="navbar-form navbar-left" method="get"
      action="{% url 'search' %}">
    <div class="form-group">
        <input id="inputSearch" name="query" class="text-info form-control"
               type="text"
               placeholder="Search"
               value="{{ request.GET.search }}">
        <input class="btn btn-default" type="submit" value="Search">
    </div>
</form>

src/templates/search_page.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/search_page.css' %}">
    <link rel="stylesheet" href="{% static 'css/drop_down_btn.css' %}">
{% endblock %}

{% block title %}
    Search result
{% endblock %}

{% block content %}
    {# Hidden field to hold search query which entered by user in the previous page #}
    <input id="queryHolder" type="hidden" query-data="{{ query }}"></input>
    <div class="container">
        <div class="row-fluid">
            <div class="col-md-3 col-sm-3">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Filter
                    </div>
                    <div class="panel-body">
                        <div>
                            <strong>Search in forum:</strong>
                            <a id="subForumSelect"
                               class="btn btn-primary btn-select btn-select-light">
                                <input type="hidden" class="btn-select-input"
                                       id=""
                                       name="" value=""/>
                                <span
                                    class="btn-select-value">Select an Item</span>
                                <span
                                    class='btn-select-arrow glyphicon glyphicon-chevron-down'></span>
                                <ul id="subForumList">
                                    <li class="selected">All</li>
                                </ul>
                            </a>
                        </div>
                        <div>
                            <strong>Filter by like or view</strong>
                            <a id="filterSelect"
                               class="btn btn-primary btn-select btn-select-light">
                                <input type="hidden" class="btn-select-input"
                                       id=""
                                       name="" value=""/>
                                <span
                                    class="btn-select-value">Select an Item</span>
                                <span
                                    class='btn-select-arrow glyphicon glyphicon-chevron-down'></span>
                                <ul id="">
                                    <li class="selected">None</li>
                                    <li>Most commented</li>
                                    <li>Total likes descending</li>
                                    <li>Total likes ascending</li>
                                    <li>Total views descending</li>
                                    <li>Total views ascending</li>
                                </ul>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div id="" class="col-md-9 col-sm-9">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Results
                    </div>
                    <div id="resultPanelBody" class="panel-body">
                        <div id="resultCounter" class="">
                        </div>
                        <div id="paginator" class=""
                             style="">
                            <ul class="pagination list-inline">
                                <li id="btnPrev"><span>&laquo;</span></li>
                                <li class="disabled"><span id="pageCounter">Pagecount</span>
                                </li>
                                <li id="btnNext"><span>&raquo;</span></li>
                            </ul>
                        </div>
                        <div id="resultContainer">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script>
        function change_tab(id) {
            document.getElementById("page_content").innerHTML = document.getElementById(id + "_desc").innerHTML;
            document.getElementById("page1").className = "notselected";
            document.getElementById("page2").className = "notselected";
            document.getElementById("page3").className = "notselected";
            document.getElementById(id).className = "selected";
        }
    </script>
    <script src="{% static 'js/search_page.js' %}"></script>
{% endblock %}