src/accounts/api/urls.py
from django.conf.urls import url
from rest_framework.routers import DefaultRouter

from accounts.api.views import (
    UserListAPIView,
    StudentProfileViewset,
    ResetPasswordToDefault,
)

router = DefaultRouter()
router.register('', StudentProfileViewset, base_name='account')

urlpatterns = [
    url(r'^user_list/$', UserListAPIView.as_view(), name='user_list'),
    url(r'^reset_pass/$', ResetPasswordToDefault.as_view(), name='reset_pass'),
]

src/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from .views import (
    user_profile,
    user_profile_edit,
    update_profile,
    user_login,
    change_password,
    user_activity,
)
from .resetpass import ResetPasswordRequestView, PasswordResetConfirmView

app_name = 'accounts'

urlpatterns = [
    url(r'^login-site/', user_login, name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^password-change/$', change_password, name='password-change'),
    url(r'^(?P<student_id>\d+)/profile/$', user_profile, name='profile'),
    url(r'^(?P<student_id>\d+)/activity/$', user_activity, name='activity'),
    url(r'^(?P<student_id>\d+)/profile/edit/$', user_profile_edit,
        name='profile-edit'),
    url(r'^(?P<student_id>\d+)/profile/api/update-info/$', update_profile,
        name='profile-update'),
    url(r'^reset_password/$', ResetPasswordRequestView.as_view(),
        name='reset_password'),
    url(
        r'^reset_password_confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        PasswordResetConfirmView.as_view(), name='reset_password_confirm')
]

src/student_info_site/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from accounts.api.urls import router as account_router
from subjects.api.urls import router as subject_router
from comments.api.urls import router as comment_router
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home_page, name='home'),
    url(r'^404', views.error_404, name='error_404'),
    url(r'^403', views.error_403, name='error_403'),
    url(r'^400', views.error_400, name='error_400'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^forum/', include('subforums.urls', namespace='forum')),
    url(r'^threads/', include('threads.urls', namespace='threads')),
    url(r'^search/', views.search, name='search'),
    url(r'^api/subforum/', include(
        'subforums.api.urls', namespace='subforum-api')),
    url(r'^api/thread/', include('threads.api.urls', namespace='thread-apis')),
    url(r'^api/account/',
        include(account_router.urls, namespace='account-api')),
    url(r'^api/accounts/',
        include('accounts.api.urls', namespace='accounts-api')),
    url(r'^student/', include('subjects.urls', namespace='student')),
    url(r'^student_admin/',
        include('admin_student.urls', namespace='student_admin')),
    url(r'^api/subject-mark/',
        include(subject_router.urls, namespace='subject-api')),
    url(r'^api/comment/',
        include(comment_router.urls, namespace='comment-api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/threads/urls.py
from django.conf.urls import url, include
from .views import (
    post_thread,
    thread_detail_view,
    ThreadUpdateView,
    pin_thread,
    UserThreadDraftList,
)

app_name = 'threads'

urlpatterns = [
    url(r'^show/(?P<pk>\d+)/$', thread_detail_view, name='detail'),
    url(r'^(?P<pk>\d+)/edit/$', ThreadUpdateView.as_view(), name='edit'),
    url(r'^(?P<thread_id>\d+)/pin/$', pin_thread, name='pin'),
    url(r'^draft/$', UserThreadDraftList.as_view(), name='draft'),
    url(r'^create/$', post_thread, name='create'),
    url(r'^comments/', include('comments.urls', namespace='comments')),
]

src/accounts/models.py
import datetime
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.models import BaseUserManager
from django.urls import reverse
from django.db.models.signals import post_save


class StudentProfileManager(BaseUserManager):
    def create_user(self, name, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        user = self.model(name=name, **extra_fields)
        user.password = password
        user.save(using=self._db)
        return user

    def create_superuser(self, name, password=None,
                         **extra_fields):
        extra_fields['status'] = StudentProfile.ADMIN
        user = self.create_user(name=name, password=password,
                                **extra_fields)
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)


def convert_student_id(id):
    # student_id first part is current year,
    # last part is user id with 4 number formatted
    student_id_first_part = datetime.datetime.now().year
    student_id_last_part = '{0:0{width}}'.format(int(id), width=4)
    return '{}{}'.format(student_id_first_part, student_id_last_part)


def create_student_email(id):
    return '{}@hust.edu.vn'.format(convert_student_id(id))


class StudentProfile(AbstractBaseUser, PermissionsMixin):
    STUDYING = 'ST'
    GRADUATED = 'GT'
    ADMIN = 'AD'

    STATUS_CHOICES = (
        (STUDYING, 'Studying'),
        (GRADUATED, 'Graduated'),
        (ADMIN, 'Administrator')
    )

    student_id = models.CharField(max_length=8, unique=True)
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255, blank=True)
    private_email = models.EmailField(max_length=255, default='',
                                      null=True, blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics/',
                                    default='images/user-default.jpg')
    status = models.CharField(max_length=2, choices=STATUS_CHOICES,
                              default=STUDYING)
    date_of_birth = models.DateField(max_length=8, default='2017-01-01')
    # True is male,False is female
    gender = models.BooleanField(default=True)
    joined_time = models.DateField(auto_now=True)
    graduated_year = models.DateField(blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    home_address = models.CharField(max_length=256, null=True, blank=True,
                                    default='')
    mobile_phone = models.CharField(max_length=12, null=True, blank=True,
                                    default='')
    objects = StudentProfileManager()

    USERNAME_FIELD = 'student_id'
    REQUIRED_FIELDS = ['name', 'email']

    class Meta:
        db_table = 'StudentProfiles'

    def get_gender(self):
        if self.gender:
            return 'Male'
        return 'Female'

    def get_absolute_url(self):
        return reverse('accounts:profile',
                       kwargs={'student_id': self.student_id})

    def get_thread_list_api(self):
        return reverse('thread-apis:user_thread')

    def get_comment_list_api(self):
        return reverse('comment-apis:user_comment')

    def get_activity_link(self):
        return reverse('accounts:activity',
                       kwargs={'student_id': self.student_id})

    def get_update_url(self):
        return reverse('accounts:profile-update',
                       kwargs={'student_id': self.student_id})

    def get_avtivity_link(self):
        return reverse('accounts:activity',
                       kwargs={'student_id': self.student_id})

    def get_full_name(self):
        return self.name

    def get_short_name(self):
        return self.name

    def __str__(self):
        return self.name


def post_save_student_receiver(sender, instance, created, *args, **kwargs):
    if created:
        instance.set_password(instance.password)
        instance.student_id = convert_student_id(instance.id)
        instance.email = create_student_email(instance.id)
        instance.save()


post_save.connect(post_save_student_receiver, sender=StudentProfile)

src/accounts/forms.py
import re
from django import forms


class StudentUpdateForm(forms.Form):
    email = forms.EmailField(max_length=250)
    phone = forms.CharField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['phone'].required = False
        self.fields['email'].required = False

    class Meta:
        fields = ['email', 'phone', ]

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        if not phone:
            return phone
        if not re.search('[0-9]', phone):
            raise forms.ValidationError(
                'Mobile phone number can not contain letters from alphabet')
        if len(phone) not in (10, 11):
            raise forms.ValidationError(
                'Mobile phone number must be 10 or 11 characters')
        return phone


class PasswordResetRequestForm(forms.Form):
    student_id = forms.CharField(label='Student ID',
                                 max_length=8,
                                 min_length=8)


class SetPasswordForm(forms.Form):
    error_messages = {
        'password_mismatch': ("The two password fields didn't match."),
    }
    new_password1 = forms.CharField(label=("New password"),
                                    widget=forms.PasswordInput)
    new_password2 = forms.CharField(label=("New password confirmation"),
                                    widget=forms.PasswordInput)

    def clean_new_password2(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',
                )
        return password2

src/accounts/api/views.py
from rest_framework import viewsets
from rest_framework.generics import ListAPIView
from rest_framework.views import APIView
from rest_framework import permissions
from rest_framework import filters
from rest_framework.response import Response
from rest_framework import status
from .serializers import (StudentProfileSerializer,
                          StudentProfileCreateSerializer)
from accounts.models import StudentProfile

DEFAULT_PASS = 'hust1234'


class UserListAPIView(ListAPIView):
    serializer_class = StudentProfileSerializer
    permission_classes = (permissions.IsAdminUser,)

    def get_queryset(self):
        return StudentProfile.objects.all().order_by('student_id')


class ResetPasswordToDefault(APIView):
    permission_classes = (permissions.IsAdminUser,)

    def put(self, request):
        student_id = request.POST.get('student_id')
        try:
            student = StudentProfile.objects.get(student_id=student_id)
        except:
            return Response(status=status.HTTP_404_NOT_FOUND)
        student.set_password(DEFAULT_PASS)
        student.save()
        return Response(status=status.HTTP_200_OK)


class StudentProfileViewset(viewsets.ModelViewSet):
    permission_classes = (permissions.IsAdminUser,)
    serializer_class = StudentProfileSerializer
    queryset = StudentProfile.objects.all()
    filter_backends = (filters.SearchFilter,)
    search_fields = ('student_id', 'name', 'email', 'private_email',)
    lookup_field = 'student_id'

    def get_serializer_class(self):
        if self.action == 'create':
            return StudentProfileCreateSerializer
        return StudentProfileSerializer

    def destroy(self, request, *args, **kwargs):
        user = self.get_object()
        if user.student_id != self.request.user.student_id:
            self.perform_destroy(user)
            return Response(status=status.HTTP_204_NO_CONTENT)
        return Response({'result': "Can't delete yourself!"},
                        status=status.HTTP_400_BAD_REQUEST)

src/accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.http.response import (
    JsonResponse,
    HttpResponseRedirect,
)
from django.shortcuts import render, redirect
from django.views.decorators.http import require_http_methods
from django.core.urlresolvers import reverse, reverse_lazy
from rest_framework import status
from . import forms
from . import models


@login_required(login_url=reverse_lazy('accounts:login'))
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request,
                             'Your password was successfully updated!')
            return HttpResponseRedirect(reverse('accounts:profile', kwargs={
                'student_id': request.user.student_id}))
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/change-password.html', {
        'form': form
    })


@login_required(login_url=reverse_lazy('accounts:login'))
def user_activity(request, student_id):
    try:
        student = models.StudentProfile.objects.get(student_id=student_id)
    except:
        return render(request, 'error_404.html')
    return render(request, 'accounts/user_activity.html',
                  {'student': student, 'is_edit': False, 'is_info': False})


@login_required(login_url=reverse_lazy('accounts:login'))
def user_profile(request, student_id):
    try:
        student = models.StudentProfile.objects.get(student_id=student_id)
    except:
        return render(request, 'error_404.html')
    return render(request, 'accounts/user_personal_info.html',
                  {'student': student, 'is_edit': False, 'is_info': True})


@login_required(login_url=reverse_lazy('accounts:login'))
def user_profile_edit(request, student_id):
    if request.user.student_id != student_id:
        return render(request, 'error_403.html')
    try:
        student = models.StudentProfile.objects.get(student_id=student_id)
    except:
        return render(request, 'error_404.html')
    return render(request, 'accounts/user_personal_info.html',
                  {'student': student, 'is_edit': True, 'is_info': True})


def user_login(request):
    next_url = request.POST.get('next')
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('home'))
    if request.method != 'POST':
        return render(request, 'accounts/login.html',
                      {'is_error': False, 'next': request.GET.get('next')})
    student_id = request.POST.get('student_id')
    password = request.POST.get('password')

    user = authenticate(username=student_id, password=password)
    if user is None:
        return render(request, 'accounts/login.html',
                      {'is_error': True, 'next': next_url})
        # return HttpResponseRedirect(
        #     reverse('accounts:login') + '?next=' + next_url, status=404)
    login(request, user)
    return HttpResponseRedirect(request.POST.get('next', reverse('home')))


@require_http_methods(['POST'])
def update_profile(request, student_id):
    user = request.user
    if user.student_id != student_id:
        return render(request, 'error_403.html')
    validate_form = forms.StudentUpdateForm(request.POST)
    if not validate_form.is_valid():
        return JsonResponse(
            {'success': False, 'email': validate_form.errors.get('email', ''),
             'phone': validate_form.errors.get('phone','')},
            status=status.HTTP_400_BAD_REQUEST)
    user.private_email = request.POST['email']
    user.mobile_phone = request.POST['phone']
    user.home_address = request.POST['address']
    if 'profile_pic' in request.FILES:
        user.profile_pic = request.FILES.get('profile_pic')
    user.save()
    return JsonResponse({'success': True, 'email': True},
                        status=status.HTTP_200_OK)

src/accounts/templates/accounts/change-password.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}
    Change password
{% endblock %}

{% block content %}
    <div class="container col-md-6 col-md-offset-3">
        <div class="panel panel-info">
            <div class="panel-heading">
                <strong> Change password</strong>
            </div>
            <div class="panel-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="control-label"
                               for="id_old_password">Current password</label>
                        <input type="password"
                               name="old_password"
                               autofocus=""
                               class="form-control"
                               placeholder="Old password"
                               title="" required=""
                               id="id_old_password"></div>
                    <div class="form-group">
                        <label class="control-label"
                               for="id_new_password1">New password</label>
                        <input type="password"
                               name="new_password1"
                               class="form-control"
                               placeholder="New password"
                               title="Your password can&amp;#39;t be too similar to your other personal information.Your password must contain at least 8 characters.Your password can&amp;#39;t be a commonly used password.Your password can&amp;#39;t be entirely numeric."
                               required=""
                               id="id_new_password1">
                        <div class="help-block">
                            <ul>
                                <li>Your password can't be too similar to
                                    your other personal information.
                                </li>
                                <li>Your password must contain at least 8
                                    characters.
                                </li>
                                <li>Your password can't be a commonly used
                                    password.
                                </li>
                                <li>Your password can't be entirely
                                    numeric.
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="form-group"><label class="control-label"
                                                   for="id_new_password2">New
                        password confirmation</label><input type="password"
                                                            name="new_password2"
                                                            class="form-control"
                                                            placeholder="New password confirmation"
                                                            title=""
                                                            required=""
                                                            id="id_new_password2">
                    </div>
                    <button type="submit" class="btn btn-success">
                        Submit
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

src/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block title %}
    Login
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="card-login card-container">
            <img id="profile-img" class="profile-img-card"
                 src="//ssl.gstatic.com/accounts/ui/avatar_2x.png"/>
            <p id="profile-name" class="profile-name-card"></p>
            <form class="form-signin" method="post"
                  action="{% url 'accounts:login' %}">
                {% csrf_token %}
                <span id="reauth-email" class="reauth-email"></span>
                <input
                    type="text" id="inputStdID"
                    class="form-control"
                    name="student_id"
                    placeholder="Student ID"
                    required autofocus>
                <input type="hidden" name="next" value="{{ next }}">
                <input
                    type="password"
                    name="password"
                    id="inputPassword"
                    class="form-control"
                    placeholder="Password" required>
                <button class="btn btn-lg btn-primary btn-block btn-signin"
                        type="submit">Sign in
                </button>
                {% if is_error %}
                    <div class="alert alert-danger text-center" role="alert">
                        <strong>Ooops!</strong>
                        Wrong student id or password,please try again!
                    </div>
                {% endif %}
            </form><!-- /form -->
            <a href="{% url 'accounts:reset_password' %}" class="forgot-password">
                Forgot the password?
            </a>
        </div><!-- /card-container -->
    </div>
{% endblock %}

src/accounts/templates/accounts/password_reset_subject.html
Password Reset

src/accounts/templates/accounts/user-profile.html
{% extends 'base.html' %}
{% block title %}
    {{ user.name }}
{% endblock %}

{% block content %}
    <div class="container" xmlns="http://www.w3.org/1999/html">
        <div class="row">
            <div
                class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h3 class="panel-title">Personal Information</h3>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-4 col-lg-4" align="center">
                                <img
                                    alt="User Pic"
                                    src="{{ user.profile_pic.url }}"
                                    width="300px"
                                    height="300px"
                                    class="img-circle img-responsive">
                                {% if is_edit %}
                                    <form
                                        id="form-image"
                                        enctype="multipart/form-data"
                                        data="{{ user.get_absolute_url }}"
                                        data-href="{{ user.get_image_upload_url }}">
                                        {% csrf_token %}
                                        <input
                                            id="input-image"
                                            type="file"
                                            class="file btn btn-info"
                                            data-show-preview="false"
                                            style="margin-top: 20px;width: 150px">
                                        <button class="btn btn-primary"
                                                style="margin-top: 20px"
                                                type="submit">Upload
                                        </button>
                                    </form>
                                {% endif %}
                            </div>
                            <div class=" col-md-8 col-lg-8 ">
                                <form
                                    id="user-edit-form"
                                    data="{{ user.get_absolute_url }}"
                                    data-href="{{ user.get_update_url }}">
                                    <table
                                        class="table table-user-information">
                                        {% csrf_token %}
                                        <tbody>
                                            <tr>
                                                <td>Name</td>
                                                <td>{{ user.name }}</td>
                                            </tr>
                                            <tr>
                                                <td>Student Id</td>
                                                <td>{{ user.student_id }}</td>
                                            </tr>
                                            <tr>
                                                <td>Status</td>
                                                <td>{{ user.get_status_display }}</td>
                                            </tr>
                                            <tr>
                                                <td>Joined date</td>
                                                <td>{{ user.joined_time }}</td>
                                            </tr>
                                            <tr>
                                                <td>Date of Birth</td>
                                                <td>{{ user.date_of_birth }}</td>
                                            </tr>
                                            <tr>
                                            <tr>
                                                <td>Gender</td>
                                                <td>{{ user.get_gender }}</td>
                                            </tr>
                                            <tr>
                                                <td>Home Address</td>
                                                {% if is_edit %}
                                                    <td><input
                                                        id="input-address"
                                                        type="text"
                                                        class="form-control"
                                                        value="{{ user.home_address }}">
                                                    </td>
                                                {% else %}
                                                    <td>{{ user.home_address }}</td>
                                                {% endif %}
                                            </tr>
                                            <tr>
                                                <td>Email</td>
                                                <td>{{ user.email }}</td>
                                            </tr>
                                            <tr>
                                                <td>Private Email</td>
                                                {% if is_edit %}
                                                    <td><input
                                                        id="input-email"
                                                        type="text"
                                                        class="form-control"
                                                        value="{{ user.private_email }}">
                                                    </td>
                                                {% else %}
                                                    <td>{{ user.private_email }}</td>
                                                {% endif %}
                                            </tr>
                                            <tr>
                                                <td>Phone Number</td>
                                                {% if is_edit %}
                                                    <td><input
                                                        id="input-phone"
                                                        type="text"
                                                        class="form-control"
                                                        value="{{ user.mobile_phone }}">
                                                    </td>
                                                {% else %}
                                                    <td>{{ user.mobile_phone }}</td>
                                                {% endif %}
                                            </tr>
                                        </tbody>
                                    </table>
                                    <div class="col-lg-3 col-md-3"
                                         style="text-align: center">
                                        {% if is_edit %}
                                            <button type="submit"
                                                    class=" btn btn-primary">
                                                Save
                                            </button>
                                        {% endif %}
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <a
                            href="{% url 'accounts:password-change' student_id=user.student_id %}"
                            data-original-title="Broadcast Message"
                            data-toggle="tooltip" type="button"
                            class="btn btn-sm btn-primary"><i
                            class="glyphicon glyphicon-wrench"></i>Change
                            password</a>
                        <span class="pull-right">
                            {% if user.student_id == student_id and not is_edit %}
                                <a href="{% url 'accounts:profile-edit' student_id=user.student_id %}"
                                   data-original-title="Edit this user"
                                   data-toggle="tooltip" type="button"
                                   class="btn btn-sm btn-warning"><i
                                    class="glyphicon glyphicon-edit"></i>Edit profile</a>
                            {% endif %}
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}