src/admin_student/urls.py
from django.conf.urls import url

from . import views

app_name = 'student_admin'

urlpatterns = [
    url(r'^subforum/(?P<slug>[-\w]+)/drafts/$', views.subforum_draft_list,
        name='drafts'),
    url(r'^index/$', views.UserListView.as_view(), name='user-list'),
    url(r'^subject/$', views.SubjectListView.as_view(), name='subject-list'),
    url(r'^user/(?P<student_id>\d+)/transcript/$',
        views.MarkListView.as_view(), name='transcript'),
]

src/student_info_site/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from accounts.api.urls import router as account_router
from subjects.api.urls import router as subject_router
from comments.api.urls import router as comment_router
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home_page, name='home'),
    url(r'^404', views.error_404, name='error_404'),
    url(r'^403', views.error_403, name='error_403'),
    url(r'^400', views.error_400, name='error_400'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^forum/', include('subforums.urls', namespace='forum')),
    url(r'^threads/', include('threads.urls', namespace='threads')),
    url(r'^search/', views.search, name='search'),
    url(r'^api/subforum/', include(
        'subforums.api.urls', namespace='subforum-api')),
    url(r'^api/thread/', include('threads.api.urls', namespace='thread-apis')),
    url(r'^api/account/',
        include(account_router.urls, namespace='account-api')),
    url(r'^api/accounts/',
        include('accounts.api.urls', namespace='accounts-api')),
    url(r'^student/', include('subjects.urls', namespace='student')),
    url(r'^student_admin/',
        include('admin_student.urls', namespace='student_admin')),
    url(r'^api/subject-mark/',
        include(subject_router.urls, namespace='subject-api')),
    url(r'^api/comment/',
        include(comment_router.urls, namespace='comment-api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/subjects/urls.py
from django.conf.urls import url
from .views import SubjectListView

app_name = 'student'

urlpatterns = [
    url(r'^transcript/$', SubjectListView.as_view(), name='transcript'),
]

src/threads/urls.py
from django.conf.urls import url, include
from .views import (
    post_thread,
    thread_detail_view,
    ThreadUpdateView,
    pin_thread,
    UserThreadDraftList,
)

app_name = 'threads'

urlpatterns = [
    url(r'^show/(?P<pk>\d+)/$', thread_detail_view, name='detail'),
    url(r'^(?P<pk>\d+)/edit/$', ThreadUpdateView.as_view(), name='edit'),
    url(r'^(?P<thread_id>\d+)/pin/$', pin_thread, name='pin'),
    url(r'^draft/$', UserThreadDraftList.as_view(), name='draft'),
    url(r'^create/$', post_thread, name='create'),
    url(r'^comments/', include('comments.urls', namespace='comments')),
]

src/admin_student/models.py
from django.db import models

# Create your models here.

src/subjects/models.py
from django.db import models
import datetime
from accounts.models import StudentProfile
from subforums import models as forum_models


class Subject(models.Model):
    title = models.CharField(max_length=255)
    credit = models.IntegerField()
    subject_id = models.CharField(max_length=8, unique=True)
    short_name = models.CharField(max_length=20)

    def save(self, *args, **kwargs):
        # Auto create a subforum for this subject
        super(Subject, self).save(*args, **kwargs)
        subforum = forum_models.Subforum.objects.get_or_create(subject=self)[0]
        subforum.title = self.title
        subforum.short_name = self.short_name
        subforum.save()

    class Meta:
        db_table = 'Subjects'

    def __str__(self):
        return self.title


class Mark(models.Model):
    PASS = 'PS'
    NOT_PASS = 'NP'

    MARK_STATUS = (
        (PASS, 'PASS'),
        (NOT_PASS, 'NOT PASS'),
    )
    YEAR_CHOICES = [(r, r) for r in
                    range(2010, datetime.date.today().year + 1)]

    student = models.ForeignKey(StudentProfile, related_name='marks')
    subject = models.ForeignKey(Subject, related_name='mark')
    year = models.IntegerField(choices=YEAR_CHOICES,
                               default=datetime.datetime.now().year)
    mid_term_mark = models.FloatField()
    final_mark = models.FloatField()
    status = models.CharField(max_length=2, choices=MARK_STATUS,
                              default=NOT_PASS)
    avg_mark = models.FloatField()

    class Meta:
        db_table = 'Marks'

    def save(self, *args, **kwargs):
        self.avg_mark = (self.mid_term_mark + self.final_mark) / 2
        self.status = self.PASS
        if self.mid_term_mark < 3 or self.final_mark < 3 or self.avg_mark < 4:
            self.status = self.NOT_PASS
        super().save(*args, **kwargs)

    def __str__(self):
        return "{}'s {} mark".format(self.student.name, self.subject.title)

src/threads/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.utils.text import slugify
from subforums.models import Subforum
from accounts.models import StudentProfile


class Thread(models.Model):
    subforum = models.ForeignKey(Subforum, related_name='threads')
    title = models.CharField(max_length=350)
    content = models.TextField()
    content_html = models.TextField(editable=False, default='', blank=True)
    author = models.ForeignKey(StudentProfile, related_name='threads')
    likes = models.ManyToManyField(StudentProfile, related_name='thread_likes',
                                   blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    published_date = models.DateTimeField(blank=True, null=True)
    is_pinned = models.BooleanField(default=False)
    view_count = models.IntegerField(default=0)

    class Meta:
        db_table = 'Threads'

    def increase_view(self):
        self.view_count += 1
        self.save()

    def summarize_content(self):
        if len(self.content) > 30:
            return '{}....'.format(self.content[:30])
        return self.content

    def get_detail_link(self):
        return reverse('threads:detail', kwargs={'pk': self.pk})

    def get_image_file_name(self, filename):
        slug = slugify(self.title)
        return 'thread_images/{}-{}'.format(slug, filename)

    def get_publish_url(self):
        return reverse('thread-apis:publish', kwargs={'pk': self.pk})

    def get_like_url(self):
        return reverse('thread-apis:like-toggle', kwargs={'pk': self.pk})

    def get_delete_api_url(self):
        return reverse('thread-apis:delete', kwargs={'pk': self.pk})

    def get_check_like_url(self):
        return reverse('thread-apis:check-like', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


class ThreadImages(models.Model):
    thread = models.ForeignKey(Thread, related_name='images')
    image = models.ImageField(upload_to='thread_images/', )

    def delete(self, using=None, keep_parents=False):
        self.image.delete()
        super().delete(using=using, keep_parents=keep_parents)

    def __str__(self):
        return self.image.name

src/admin_student/views.py
from braces.views._access import SuperuserRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.db.models import Q
from accounts.models import StudentProfile
from subjects.models import Subject, Mark
from subforums.models import Subforum
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

ITEMS_PER_PAGE = 7


@login_required(login_url='/accounts/login-site/')
def index(request):
    return render(request, 'admin_student/admin_base.html', {})


class SubjectListView(SuperuserRequiredMixin, ListView):
    template_name = 'admin_student/subject.html'
    login_url = '/accounts/login-site'
    model = Subject
    context_object_name = 'subject_list'

    def get_queryset(self):
        subjects = Subject.objects.all()
        query = self.request.GET.get('query')
        if query:
            subjects = subjects.filter(
                Q(subject_id__icontains=query) |
                Q(title__icontains=query)
            )
        page = self.request.GET.get('page', 1)
        paginator = Paginator(subjects, ITEMS_PER_PAGE)
        try:
            subject_list = paginator.page(page)
        except PageNotAnInteger:
            subject_list = paginator.page(1)
        except EmptyPage:
            subject_list = paginator.num_pages(paginator.num_pages)
        return subject_list


class MarkListView(SuperuserRequiredMixin, ListView):
    template_name = 'admin_student/transcript.html'
    login_url = 'accounts/login-site'
    model = Mark
    context_object_name = 'mark_list'

    def get_queryset(self):
        student_id = self.kwargs.get('student_id')
        queryset = Mark.objects.filter(
            student__student_id=student_id
        ).order_by('year')
        return queryset

    def get_context_data(self, **kwargs):
        student_id = self.kwargs.get('student_id')
        subject_list = Subject.objects.exclude(
            mark__student__student_id=student_id
        ).order_by('title')
        kwargs['subject_list'] = subject_list
        kwargs['student'] = get_object_or_404(StudentProfile,
                                              student_id=student_id)
        return super().get_context_data(**kwargs)


class UserListView(ListView):
    template_name = 'admin_student/user_list.html'
    login_url = '/accounts/login-site'
    model = StudentProfile
    context_object_name = 'student_list'

    def get_queryset(self):
        queryset = StudentProfile.objects.all()
        search_query = self.request.GET.get('search')
        if search_query:
            queryset = queryset.filter(
                Q(name__icontains=search_query) |
                Q(private_email__icontains=search_query) |
                Q(email__icontains=search_query) |
                Q(student_id__icontains=search_query)
            )
        page = self.request.GET.get('page', 1)
        paginator = Paginator(queryset, ITEMS_PER_PAGE)
        try:
            users = paginator.page(page)
        except PageNotAnInteger:
            users = paginator.page(1)
        except EmptyPage:
            users = paginator.num_pages(paginator.num_pages)
        return users

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseRedirect(reverse_lazy('accounts:login'))
        if not request.user.is_superuser:
            return render(request, 'error_403.html')
        return super().dispatch(request, *args, **kwargs)


@login_required(login_url=reverse_lazy('accounts:login'))
def subforum_draft_list(request, slug):
    if not request.user.is_superuser:
        return render(request, 'error_403.html')
    subforum = get_object_or_404(Subforum, slug=slug)
    thread_list = subforum.threads.filter(
        published_date__isnull=True
    ).order_by(
        '-created_date'
    )
    page = request.GET.get('page', 1)
    paginator = Paginator(thread_list, ITEMS_PER_PAGE)
    try:
        threads = paginator.page(page)
    except PageNotAnInteger:
        threads = paginator.page(1)
    except EmptyPage:
        threads = paginator.num_pages(paginator.num_pages)
    context_dict = {
        'subforum': subforum,
        'thread_list': threads,
        'is_draft': True
    }
    return render(request, 'admin_student/forum.html', context_dict)


@login_required(login_url='/accounts/login-site/')
def user_list(request):
    if request.user.is_superuser:
        return render(request, 'admin_student/user_list.html', {})
    return render(request, 'error_403.html', {})

src/subjects/api/views.py
from rest_framework.viewsets import ModelViewSet
from rest_framework import permissions
from . import serializers
from subjects.models import Subject, Mark


class SubjectViewSet(ModelViewSet):
    serializer_class = serializers.SubjectSerializer
    permission_classes = (permissions.IsAdminUser,)
    queryset = Subject.objects.all()
    lookup_field = 'subject_id'


class MarkViewSet(ModelViewSet):
    serializer_class = serializers.MarkSerializer
    permission_classes = (permissions.IsAdminUser,)
    queryset = Mark.objects.all()

src/subjects/views.py
from django.views.generic import ListView
from braces.views import LoginRequiredMixin
from .models import Mark


class SubjectListView(LoginRequiredMixin, ListView):
    template_name = 'subjects/transcript.html'
    context_object_name = 'mark_list'
    login_url = '/accounts/login-site'
    model = Mark

    def get_queryset(self):
        return Mark.objects.filter(student=self.request.user).order_by('year')

src/admin_student/templates/admin_student/admin_base.html
<!DOCTYPE html>
{% load staticfiles %}
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}{% endblock %}</title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta
            content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
            name="viewport">
        <link rel="stylesheet"
              href="{% static 'bootstrap/css/bootstrap.min.css' %}">
        <!-- Font Awesome -->
        <link rel="stylesheet"
              href="{% static 'admin_student/font-awesome/css/font-awesome.min.css' %}">
        <!-- Ionicons -->
        <link rel="stylesheet"
              href="{% static 'admin_student/ionicons/css/ionicons.css' %}">
        <!-- Theme style -->
        <link rel="stylesheet"
              href="{% static 'admin_student/dist/css/AdminLTE.min.css' %}">
        <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
              page. However, you can choose any other skin. Make sure you
              apply the skin class to the body tag so the changes take effect. -->
        <link rel="stylesheet"
              href="{% static 'admin_student/dist/css/skins/skin-blue.min.css' %}">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        {#        <!--[if lt IE 9]>#}
        <script
            src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script
            src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        <!-- Google Font -->
        <link rel="stylesheet"
              href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
        {% block css %}{% endblock %}
    </head>
    <!--
    BODY TAG OPTIONS:
    =================
    Apply one or more of the following classes to get the
    desired effect
    |---------------------------------------------------------|
    | SKINS         | skin-blue                               |
    |               | skin-black                              |
    |               | skin-purple                             |
    |               | skin-yellow                             |
    |               | skin-red                                |
    |               | skin-green                              |
    |---------------------------------------------------------|
    |LAYOUT OPTIONS | fixed                                   |
    |               | layout-boxed                            |
    |               | layout-top-nav                          |
    |               | sidebar-collapse                        |
    |               | sidebar-mini                            |
    |---------------------------------------------------------|
    -->
    <body class="hold-transition skin-blue sidebar-mini">
        <div class="wrapper">
            <!-- Main Header -->
            <header class="main-header">
                <!-- Logo -->
                <a href="index2.html" class="logo">
                    <!-- mini logo for sidebar mini 50x50 pixels -->
                    <span class="logo-mini"><b>AD</b></span>
                    <!-- logo for regular state and mobile devices -->
                    <span class="logo-lg"><b>Student Admin</b></span>
                </a>
                <!-- Header Navbar -->
                <nav class="navbar navbar-static-top" role="navigation">
                    <!-- Sidebar toggle button-->
                    <a href="#" class="sidebar-toggle" data-toggle="push-menu"
                       role="button">
                        <span class="sr-only">Toggle navigation</span>
                    </a>
                    <!-- Navbar Right Menu -->
                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav">
                            <!-- User Account Menu -->
                            <li class="dropdown user user-menu">
                                <!-- Menu Toggle Button -->
                                <a href="#" class="dropdown-toggle"
                                   data-toggle="dropdown">
                                    <!-- The user image in the navbar-->
                                    <img
                                        src="{{ user.profile_pic.url }}"
                                        class="user-image img-responsive"
                                        alt="User Image">
                                    <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                    <span
                                        class="hidden-xs">{{ user.name }}</span>
                                </a>
                                <ul class="dropdown-menu">
                                    <!-- The user image in the menu -->
                                    <li class="user-header">
                                        <img
                                            src="{{ user.profile_pic.url }}"
                                            class="img-circle img-responsive"
                                            alt="User Image">
                                        <p>
                                            {{ user.name }}
                                            - {{ user.get_status_display }}
                                            <small>Member since Nov. 2012
                                            </small>
                                        </p>
                                    </li>
                                    <!-- Menu Body -->
                                    <!-- Menu Footer-->
                                    <li class="user-footer">
                                        <div class="pull-left">
                                            <a href="#"
                                               class="btn btn-default btn-flat">Profile</a>
                                        </div>
                                        <div class="pull-right">
                                            <a href="#"
                                               class="btn btn-default btn-flat">Sign
                                                out</a>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </nav>
            </header>
            <!-- Left side column. contains the logo and sidebar -->
            <aside class="main-sidebar">
                <!-- sidebar: style can be found in sidebar.less -->
                <section class="sidebar">
                    <!-- Sidebar user panel (optional) -->
                    <div class="user-panel">
                        <div class="pull-left image">
                            <img
                                src="{{ user.profile_pic.url }}"
                                class="img-circle" alt="User Image">
                        </div>
                        <div class="pull-left info">
                            <p>{{ user.name }}</p>
                            <!-- Status -->
                            <a href="#"><i
                                class="fa fa-circle text-success"></i>
                                {{ user.get_status_display }}</a>
                        </div>
                    </div>
                    <!-- search form (Optional) -->
                    <form action="#" method="get" class="sidebar-form">
                        <div class="input-group">
                            <input type="text" name="q" class="form-control"
                                   placeholder="Search...">
                            <span class="input-group-btn">
              <button type="submit" name="search" id="search-btn"
                      class="btn btn-flat"><i class="fa fa-search"></i>
              </button>
            </span>
                        </div>
                    </form>
                    <!-- /.search form -->
                    <!-- Sidebar Menu -->
                    <ul class="sidebar-menu" data-widget="tree">
                        <li class="header">Management</li>
                        <!-- Optionally, you can add icons to the links -->
                        <li class=""><a
                            href="{% url 'home' %}"><i
                            class="fa fa-link"></i> <span>Home</span></a></li>
                        <li class=""><a
                            href="{% url 'student_admin:user-list' %}"><i
                            class="fa fa-link"></i> <span>Users</span></a></li>
                        <li><a href="{% url 'student_admin:subject-list' %}"><i
                            class="fa fa-link"></i> <span>Subject</span></a>
                        </li>
                        <li class="treeview">
                            <a href="#"><i class="fa fa-link"></i> <span>Pending</span>
                                <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
                            </a>
                            <ul id="forumListLink" class="treeview-menu">
                            </ul>
                        </li>
                    </ul>
                    <!-- /.sidebar-menu -->
                </section>
                <!-- /.sidebar -->
            </aside>
            <!-- Content Wrapper. Contains page content -->
            <div class="content-wrapper">
                <!-- Content Header (Page header) -->
                <section class="content-header">
                    <h1>
                        {% block page_header %}{% endblock %}
                        <small>
                            {% block page_header_description %}{% endblock %}</small>
                    </h1>
                </section>
                <!-- Main content -->
                <section class="content container-fluid">
                    {% block content %}
                    {% endblock %}
                </section>
                <!-- /.content -->
            </div>
            <!-- /.content-wrapper -->
            <!-- Main Footer -->
            <footer class="main-footer">
                <!-- To the right -->
                <div class="pull-right hidden-xs">
                    Hanoi University of Science and Technology
                </div>
                <!-- Default to the left -->
                <strong>Copyright &copy; 2016 <a href="#">Company</a>.</strong>
                All rights reserved.
            </footer>
        </div>
        <!-- ./wrapper -->
        <!-- REQUIRED JS SCRIPTS -->
        <!-- jQuery 3 -->
        <script src="{% static 'jquery/jquery3.2.1.min.js' %}"></script>
        <!-- Bootstrap 3.3.7 -->
        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
        <!-- AdminLTE App -->
        <script
            src="{% static 'admin_student/dist/js/adminlte.min.js' %}"></script>
        <!-- Optionally, you can add Slimscroll and FastClick plugins.
             Both of these plugins are recommended to enhance the
             user experience. -->
    </body>
    <script src="{% static 'admin_student/js/forum_list.js' %}"></script>
    <script
        src="{% static 'admin_student/dist/js/inputmask/jquery.inputmask.js' %}"></script>
    <script
        src="{% static 'admin_student/dist/js/inputmask/jquery.inputmask.extensions.js' %}"></script>
    <script
        src="{% static 'admin_student/dist/js/inputmask/jquery.inputmask.date.extensions.js' %}"></script>
    {% block script %}{% endblock %}
</html>

src/admin_student/templates/admin_student/user_list.html
{% extends 'admin_student/admin_base.html' %}
{% load staticfiles %}

{% block title %}
    User list
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Student list</h3>
                    <div class="box-tools">
                        <form id="user-search"
                              action="{% url 'student_admin:user-list' %}"
                              class="input-group input-group-sm"
                              style="width: 150px;">
                            <input id="searchInput" type="text"
                                   name="search"
                                   class="form-control pull-right"
                                   placeholder="Search">
                            <div class="input-group-btn">
                                <button type="submit"
                                        class="btn btn-default">
                                    <i class="fa fa-search"></i></button>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table id="userTable" class="table table-hover">
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Gender</th>
                            <th>Date of birth</th>
                            <th>Email</th>
                            <th>Mobile phone
                            <th>Status</th>
                        </tr>
                        {% for student in student_list %}
                            <tr student-id="{{ student.student_id }}"
                                class="infoRow">
                                <td>{{ student.student_id }}</td>
                                <td> {{ student.name }}</td>
                                <td>{{ student.get_gender }}</td>
                                <td>{{ student.date_of_birth }}</td>
                                <td>{{ student.private_email }}</td>
                                <td>{{ student.mobile_phone }}</td>
                                <td>{{ student.get_status_display }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
                <div class="row pull-right" style="margin-right: 24px;">
                    {% if student_list.has_other_pages %}
                        <ul class="pagination">
                            {% if student_list.has_previous %}
                                <li><a
                                    href="?page={{ student_list.previous_page_number }}">&laquo;</a>
                                </li>
                            {% else %}
                                <li class="disabled"><span>&laquo;</span></li>
                            {% endif %}
                            {% for i in student_list.paginator.page_range %}
                                {% if student_list.number == i %}
                                    <li class="active"><span>{{ i }} <span
                                        class="sr-only">(current)</span></span>
                                    </li>
                                {% else %}
                                    <li><a href="?page={{ i }}">{{ i }}</a>
                                    </li>
                                {% endif %}
                            {% endfor %}
                            {% if student_list.has_next %}
                                <li><a
                                    href="?page={{ student_list.next_page_number }}">&raquo;</a>
                                </li>
                            {% else %}
                                <li class="disabled"><span>&raquo;</span></li>
                            {% endif %}
                        </ul>
                    {% endif %}
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>
    <div class="pull-left">
        <button id="btn-create-new" class="btn btn-info">Create New</button>
    </div>
    {% include 'admin_student/user-info-modal.html' %}
    {% include 'admin_student/user_create_modal.html' %}
{% endblock %}

{% block script %}
    {{ block.super }}
    <script src="{% static 'js/waiting_dialog.js' %}"></script>
    <script src="{% static 'js/users.js' %}"></script>
{% endblock %}